services:
  registry:
    image: registry:latest
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain3.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey3.pem
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "[http://registry.labs.cipriang-software.work]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "[HEAD,GET,OPTIONS,DELETE]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: "[true]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "[Authorization,Accept,Cache-Control]"
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: "[Docker-Content-Digest]"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      # Mount the password file
      - /root/registry/registry.password:/auth/registry.password
      # Mount the data directory
      - /root/registry/data:/data
      - /root/registry/certs:/certs
    ports:
      - "5000:5000"

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: unless-stopped
    ports:
      - 8085:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Lab Container Registry
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
